### PR TITLE
Update relevant-dilbert.coffee

### PR DESCRIPTION
**Pull request by shawnpetros**
added dilbert me to listeners, would be nice to do a rando as well...

### CODE REVIEW

**Comment by jonyeezs** [comment]
Hi there. Sorry not sure how i missed all your PRs.

Thanks for the contribution!

**Comment by shawnpetros** [comment]
Thanks!

**Comment by jonyeezs** [comment]
@arashcuzi would you like to open a request for the random feature?

**Comment by shawnpetros** [comment]
I definitely can! Will work on it when I get some time!

**Pull request merged**
